# initial learning rate
lr0: 0.01
# final learning rate
lrf: 0.01
# SGD momentum/Adam beta1
momentum: 0.937
# optimizer weight decay
weight_decay: 0.0005
# warmup epochs
warmup_epochs: 3.0
# warmup initial momentum
warmup_momentum: 0.8
# warmup initial bias lr
warmup_bias_lr: 0.1